Fix checking for macOS version on install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -129,13 +129,11 @@ main() {
     # readlink -f is not supported with macOS<12.3
     min_ver="12.3"
     ver=$(sw_vers -productVersion)
-    if version_gte "$ver" "$min_ver"; then
-      if [ "$ver" != "$min_ver" ]; then
-        echo "Current macOS version: $ver"
-        echo "macOS version $min_ver or higher is required"
-        echo "Please upgrade your macOS version"
-        exit 1
-      fi
+    if ! version_gte "$ver" "$min_ver"; then
+      echo "Current macOS version: $ver"
+      echo "macOS version $min_ver or higher is required"
+      echo "Please upgrade your macOS version"
+      exit 1
     fi
   fi
 
