Update to uniffi 0.24.1

diff --git a/pip-install b/pip-install
--- a/pip-install
+++ b/pip-install
@@ -7,17 +7,16 @@
 # For now clean re-installation is done on every call (more efficient
 # versioning might be added later).
 
-
 # The version UniFFI bindgen used in Python and Rust must be the same.
 # This script make sure that both match the version specified here.
-UNIFFI_BINDGEN_VERSION="0.23"
+UNIFFI_BINDGEN_VERSION="0.24.1"
 
 # The minimum version of maturin supported by this script.
 MINIMUM_MATURIN_VERSION="1.0.0"
 
 SUIBASE_DIR="$HOME/suibase"
 if [ -d "$HOME/sui-base" ] && [ ! -d "$SUIBASE_DIR" ]; then
-   ("$HOME/sui-base/repair")
+    ("$HOME/sui-base/repair")
 fi
 
 SCRIPT_COMMON_CALLER="$(readlink -f "$0")"
@@ -25,11 +24,14 @@ WORKDIR="none"
 # shellcheck source=SCRIPTDIR/scripts/common/__globals.sh
 source "$SUIBASE_DIR/scripts/common/__globals.sh" "$SCRIPT_COMMON_CALLER" "$WORKDIR"
 
-function main () {
+function main() {
     # Verify pre-requisite
-    which pip &> /dev/null || setup_error "Need to install pip. See https://pip.pypa.io/en/stable/installing/ for more info.";
+    which pip &>/dev/null || setup_error "Need to install pip. See https://pip.pypa.io/en/stable/installing/ for more info."
 
-    cd "$SUIBASE_DIR" || { echo "suibase not found. Please install it first."; exit 1; }
+    cd "$SUIBASE_DIR" || {
+        echo "suibase not found. Please install it first."
+        exit 1
+    }
 
     # Detect if in virtual environment.
     if [[ -z "$VIRTUAL_ENV" ]]; then
@@ -77,4 +79,4 @@ function main () {
     maturin develop
 }
 
-main "$@";
+main "$@"
